########################################
#             WEB SERVER              #
#######################################

mysql:
  container_name: mysql
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: mysql

mongodb:
    image: mongo:3.1.8
    container_name: mongodb
    ports:
        - "localhost:27017:27017"

redis:
  container_name: redis
  image: redis:latest
  ports:
    - "6379:6379"

php:
  container_name: php
  build: ./app/config/php-fpm/
  environment:
      - UID=1000
      - GID=1000
  links:
      - mysql:mysql
      - redis:redis
  volumes:
    - .:/var/www/nami
    - /home/geoffroy/Dev/phpink/nami-core-bundle:/var/www/nami-core-bundle

nginx:
  container_name: nginx
  build: ./app/config/nginx/
  ports:
      - "80:80"
  environment:
      VIRTUAL_HOST: nami.dev
  links:
      - php
  volumes_from:
      - php
