########################################
#             WEB SERVER              #
#######################################

mysql:
  container_name: mysql
  image: mysql:5.5
  ports:
    - "3306:3306"
  environment:
      MYSQL_ROOT_PASSWORD: root

redis:
  container_name: redis
  image: redis:latest
  ports:
    - "6379:6379"

nami:
  container_name: nginx
  build: ./app/config/nginx/
  ports:
      - "80:80"
  environment:
      VIRTUAL_HOST: nami.dev
  links:
      - mysql:mysql.dev
      - redis:redis.dev
  volumes:
    - ./app/config/nginx/nginx.conf:/etc/nginx/nginx.conf
    - .:/var/www
