liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

nami_api:
  resource: "@NamiCoreBundle/Resources/config/routing.yml"
  type:     rest
  prefix:   /api
  options:
      expose: true

nami_api_doc:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api-doc

nami_admin:
    resource: "@NamiAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

nami_front_homepage:
    path:     /
    methods:  [GET, POST]
    defaults: { _controller: NamiCoreBundle:Frontend:index }

nami_front_extra:
    path:     /test
    methods:  [GET, POST]
    defaults: { _controller: AcmeThemeBundle:Frontend:test }

nami_front_category:
    path:     /category/{slug}
    methods:  [GET, POST]
    defaults: { _controller: NamiCoreBundle:Frontend:category }
    requirements:
        slug: .+

nami_front_page:
    path:     /{slug}
    methods:  [GET, POST]
    defaults: { _controller: NamiCoreBundle:Frontend:index }
    requirements:
        slug: .+

