parameters:
  namiplugin.contactform.mail_to: "geofrwa@yandex.com"
  namiplugin.contactform.mail_template: "AcmeThemeBundle:contactform:mail.html.twig"
  namiplugin.contactform.block_template: "AcmeThemeBundle:contactform:block.html.twig"
